// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/doc.dart';
import 'api/events.dart';
import 'api/files.dart';
import 'api/handshake.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  RustStreamSink<CoreEvent> dco_decode_StreamSink_core_event_Sse(dynamic raw);

  @protected
  RustStreamSink<ProofEvent> dco_decode_StreamSink_proof_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackupView dco_decode_backup_view(dynamic raw);

  @protected
  BlockKind dco_decode_block_kind(dynamic raw);

  @protected
  BlockView dco_decode_block_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BackupView dco_decode_box_autoadd_backup_view(dynamic raw);

  @protected
  BlockKind dco_decode_box_autoadd_block_kind(dynamic raw);

  @protected
  CoreEvent dco_decode_box_autoadd_core_event(dynamic raw);

  @protected
  DocPosition dco_decode_box_autoadd_doc_position(dynamic raw);

  @protected
  DocSelection dco_decode_box_autoadd_doc_selection(dynamic raw);

  @protected
  DocumentHandle dco_decode_box_autoadd_document_handle(dynamic raw);

  @protected
  EditCommand dco_decode_box_autoadd_edit_command(dynamic raw);

  @protected
  EditOutcome dco_decode_box_autoadd_edit_outcome(dynamic raw);

  @protected
  EditResult dco_decode_box_autoadd_edit_result(dynamic raw);

  @protected
  FindQuery dco_decode_box_autoadd_find_query(dynamic raw);

  @protected
  PreferencesView dco_decode_box_autoadd_preferences_view(dynamic raw);

  @protected
  (bool, bool) dco_decode_box_autoadd_record_bool_bool(dynamic raw);

  @protected
  ScriptView dco_decode_box_autoadd_script_view(dynamic raw);

  @protected
  CoreEvent dco_decode_core_event(dynamic raw);

  @protected
  CoreInfo dco_decode_core_info(dynamic raw);

  @protected
  CrateInfo dco_decode_crate_info(dynamic raw);

  @protected
  DocPosition dco_decode_doc_position(dynamic raw);

  @protected
  DocSelection dco_decode_doc_selection(dynamic raw);

  @protected
  DocumentHandle dco_decode_document_handle(dynamic raw);

  @protected
  EditCommand dco_decode_edit_command(dynamic raw);

  @protected
  EditOutcome dco_decode_edit_outcome(dynamic raw);

  @protected
  EditRejection dco_decode_edit_rejection(dynamic raw);

  @protected
  EditResult dco_decode_edit_result(dynamic raw);

  @protected
  FindMatch dco_decode_find_match(dynamic raw);

  @protected
  FindQuery dco_decode_find_query(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InsertedBlock dco_decode_inserted_block(dynamic raw);

  @protected
  List<int> dco_decode_list_CastedPrimitive_u_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BackupView> dco_decode_list_backup_view(dynamic raw);

  @protected
  List<BlockKind> dco_decode_list_block_kind(dynamic raw);

  @protected
  List<BlockView> dco_decode_list_block_view(dynamic raw);

  @protected
  List<CrateInfo> dco_decode_list_crate_info(dynamic raw);

  @protected
  List<FindMatch> dco_decode_list_find_match(dynamic raw);

  @protected
  List<InsertedBlock> dco_decode_list_inserted_block(dynamic raw);

  @protected
  List<NewBlock> dco_decode_list_new_block(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecoveryOffer> dco_decode_list_recovery_offer(dynamic raw);

  @protected
  List<ScriptView> dco_decode_list_script_view(dynamic raw);

  @protected
  NewBlock dco_decode_new_block(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BackupView? dco_decode_opt_box_autoadd_backup_view(dynamic raw);

  @protected
  BlockKind? dco_decode_opt_box_autoadd_block_kind(dynamic raw);

  @protected
  DocSelection? dco_decode_opt_box_autoadd_doc_selection(dynamic raw);

  @protected
  DocumentHandle? dco_decode_opt_box_autoadd_document_handle(dynamic raw);

  @protected
  EditOutcome? dco_decode_opt_box_autoadd_edit_outcome(dynamic raw);

  @protected
  EditResult? dco_decode_opt_box_autoadd_edit_result(dynamic raw);

  @protected
  (bool, bool)? dco_decode_opt_box_autoadd_record_bool_bool(dynamic raw);

  @protected
  ScriptView? dco_decode_opt_box_autoadd_script_view(dynamic raw);

  @protected
  PreferencesView dco_decode_preferences_view(dynamic raw);

  @protected
  ProofEvent dco_decode_proof_event(dynamic raw);

  @protected
  (bool, bool) dco_decode_record_bool_bool(dynamic raw);

  @protected
  (int, bool) dco_decode_record_u_32_bool(dynamic raw);

  @protected
  RecoveryOffer dco_decode_recovery_offer(dynamic raw);

  @protected
  SaveFailure dco_decode_save_failure(dynamic raw);

  @protected
  SaveOutcome dco_decode_save_outcome(dynamic raw);

  @protected
  ScriptView dco_decode_script_view(dynamic raw);

  @protected
  TextMetrics dco_decode_text_metrics(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  RustStreamSink<CoreEvent> sse_decode_StreamSink_core_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProofEvent> sse_decode_StreamSink_proof_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackupView sse_decode_backup_view(SseDeserializer deserializer);

  @protected
  BlockKind sse_decode_block_kind(SseDeserializer deserializer);

  @protected
  BlockView sse_decode_block_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BackupView sse_decode_box_autoadd_backup_view(SseDeserializer deserializer);

  @protected
  BlockKind sse_decode_box_autoadd_block_kind(SseDeserializer deserializer);

  @protected
  CoreEvent sse_decode_box_autoadd_core_event(SseDeserializer deserializer);

  @protected
  DocPosition sse_decode_box_autoadd_doc_position(SseDeserializer deserializer);

  @protected
  DocSelection sse_decode_box_autoadd_doc_selection(
    SseDeserializer deserializer,
  );

  @protected
  DocumentHandle sse_decode_box_autoadd_document_handle(
    SseDeserializer deserializer,
  );

  @protected
  EditCommand sse_decode_box_autoadd_edit_command(SseDeserializer deserializer);

  @protected
  EditOutcome sse_decode_box_autoadd_edit_outcome(SseDeserializer deserializer);

  @protected
  EditResult sse_decode_box_autoadd_edit_result(SseDeserializer deserializer);

  @protected
  FindQuery sse_decode_box_autoadd_find_query(SseDeserializer deserializer);

  @protected
  PreferencesView sse_decode_box_autoadd_preferences_view(
    SseDeserializer deserializer,
  );

  @protected
  (bool, bool) sse_decode_box_autoadd_record_bool_bool(
    SseDeserializer deserializer,
  );

  @protected
  ScriptView sse_decode_box_autoadd_script_view(SseDeserializer deserializer);

  @protected
  CoreEvent sse_decode_core_event(SseDeserializer deserializer);

  @protected
  CoreInfo sse_decode_core_info(SseDeserializer deserializer);

  @protected
  CrateInfo sse_decode_crate_info(SseDeserializer deserializer);

  @protected
  DocPosition sse_decode_doc_position(SseDeserializer deserializer);

  @protected
  DocSelection sse_decode_doc_selection(SseDeserializer deserializer);

  @protected
  DocumentHandle sse_decode_document_handle(SseDeserializer deserializer);

  @protected
  EditCommand sse_decode_edit_command(SseDeserializer deserializer);

  @protected
  EditOutcome sse_decode_edit_outcome(SseDeserializer deserializer);

  @protected
  EditRejection sse_decode_edit_rejection(SseDeserializer deserializer);

  @protected
  EditResult sse_decode_edit_result(SseDeserializer deserializer);

  @protected
  FindMatch sse_decode_find_match(SseDeserializer deserializer);

  @protected
  FindQuery sse_decode_find_query(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InsertedBlock sse_decode_inserted_block(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BackupView> sse_decode_list_backup_view(SseDeserializer deserializer);

  @protected
  List<BlockKind> sse_decode_list_block_kind(SseDeserializer deserializer);

  @protected
  List<BlockView> sse_decode_list_block_view(SseDeserializer deserializer);

  @protected
  List<CrateInfo> sse_decode_list_crate_info(SseDeserializer deserializer);

  @protected
  List<FindMatch> sse_decode_list_find_match(SseDeserializer deserializer);

  @protected
  List<InsertedBlock> sse_decode_list_inserted_block(
    SseDeserializer deserializer,
  );

  @protected
  List<NewBlock> sse_decode_list_new_block(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecoveryOffer> sse_decode_list_recovery_offer(
    SseDeserializer deserializer,
  );

  @protected
  List<ScriptView> sse_decode_list_script_view(SseDeserializer deserializer);

  @protected
  NewBlock sse_decode_new_block(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BackupView? sse_decode_opt_box_autoadd_backup_view(
    SseDeserializer deserializer,
  );

  @protected
  BlockKind? sse_decode_opt_box_autoadd_block_kind(
    SseDeserializer deserializer,
  );

  @protected
  DocSelection? sse_decode_opt_box_autoadd_doc_selection(
    SseDeserializer deserializer,
  );

  @protected
  DocumentHandle? sse_decode_opt_box_autoadd_document_handle(
    SseDeserializer deserializer,
  );

  @protected
  EditOutcome? sse_decode_opt_box_autoadd_edit_outcome(
    SseDeserializer deserializer,
  );

  @protected
  EditResult? sse_decode_opt_box_autoadd_edit_result(
    SseDeserializer deserializer,
  );

  @protected
  (bool, bool)? sse_decode_opt_box_autoadd_record_bool_bool(
    SseDeserializer deserializer,
  );

  @protected
  ScriptView? sse_decode_opt_box_autoadd_script_view(
    SseDeserializer deserializer,
  );

  @protected
  PreferencesView sse_decode_preferences_view(SseDeserializer deserializer);

  @protected
  ProofEvent sse_decode_proof_event(SseDeserializer deserializer);

  @protected
  (bool, bool) sse_decode_record_bool_bool(SseDeserializer deserializer);

  @protected
  (int, bool) sse_decode_record_u_32_bool(SseDeserializer deserializer);

  @protected
  RecoveryOffer sse_decode_recovery_offer(SseDeserializer deserializer);

  @protected
  SaveFailure sse_decode_save_failure(SseDeserializer deserializer);

  @protected
  SaveOutcome sse_decode_save_outcome(SseDeserializer deserializer);

  @protected
  ScriptView sse_decode_script_view(SseDeserializer deserializer);

  @protected
  TextMetrics sse_decode_text_metrics(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_core_event_Sse(
    RustStreamSink<CoreEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_proof_event_Sse(
    RustStreamSink<ProofEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_backup_view(BackupView self, SseSerializer serializer);

  @protected
  void sse_encode_block_kind(BlockKind self, SseSerializer serializer);

  @protected
  void sse_encode_block_view(BlockView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_backup_view(
    BackupView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_block_kind(
    BlockKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_core_event(
    CoreEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_doc_position(
    DocPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_doc_selection(
    DocSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_document_handle(
    DocumentHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_command(
    EditCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_outcome(
    EditOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_result(
    EditResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_find_query(
    FindQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_preferences_view(
    PreferencesView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_bool_bool(
    (bool, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_script_view(
    ScriptView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_event(CoreEvent self, SseSerializer serializer);

  @protected
  void sse_encode_core_info(CoreInfo self, SseSerializer serializer);

  @protected
  void sse_encode_crate_info(CrateInfo self, SseSerializer serializer);

  @protected
  void sse_encode_doc_position(DocPosition self, SseSerializer serializer);

  @protected
  void sse_encode_doc_selection(DocSelection self, SseSerializer serializer);

  @protected
  void sse_encode_document_handle(
    DocumentHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_command(EditCommand self, SseSerializer serializer);

  @protected
  void sse_encode_edit_outcome(EditOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_edit_rejection(EditRejection self, SseSerializer serializer);

  @protected
  void sse_encode_edit_result(EditResult self, SseSerializer serializer);

  @protected
  void sse_encode_find_match(FindMatch self, SseSerializer serializer);

  @protected
  void sse_encode_find_query(FindQuery self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_inserted_block(InsertedBlock self, SseSerializer serializer);

  @protected
  void sse_encode_list_CastedPrimitive_u_64(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_backup_view(
    List<BackupView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_block_kind(
    List<BlockKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_block_view(
    List<BlockView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_crate_info(
    List<CrateInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_find_match(
    List<FindMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_inserted_block(
    List<InsertedBlock> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_new_block(List<NewBlock> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recovery_offer(
    List<RecoveryOffer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_script_view(
    List<ScriptView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_block(NewBlock self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_backup_view(
    BackupView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_block_kind(
    BlockKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_doc_selection(
    DocSelection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_document_handle(
    DocumentHandle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_edit_outcome(
    EditOutcome? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_edit_result(
    EditResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_bool_bool(
    (bool, bool)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_script_view(
    ScriptView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_preferences_view(
    PreferencesView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proof_event(ProofEvent self, SseSerializer serializer);

  @protected
  void sse_encode_record_bool_bool((bool, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_32_bool((int, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_recovery_offer(RecoveryOffer self, SseSerializer serializer);

  @protected
  void sse_encode_save_failure(SaveFailure self, SseSerializer serializer);

  @protected
  void sse_encode_save_outcome(SaveOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_script_view(ScriptView self, SseSerializer serializer);

  @protected
  void sse_encode_text_metrics(TextMetrics self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
