// The editor's half of the corpus-wide line-breaking differential test.
//
// `docs/LINE_BREAKING.md` is one specification with two implementations: the
// editor's `wrapText`, which runs on the keystroke path, and `layout`'s
// `line_spans`, which paginates (ADR 0018). `testdata/line-breaking.json` is
// what Rust answers for every block of the corpus, every generated edge case
// and the whole 120-page reference feature; this file asserts the editor
// answers the same, boundary for boundary.
//
// The fixture is generated by `crates/layout/tests/line_break_differential.rs`
// and regenerated on every `cargo test`, so it cannot drift from the Rust
// implementation without failing there. A failure here means the two
// implementations disagree, which is a bug on one side or the other and never a
// preference. To change the contract, change `docs/LINE_BREAKING.md`, both
// implementations, and the fixture, in one commit:
//
//     UPDATE_LINE_BREAK_FIXTURES=1 cargo test -p slugline_layout \
//         --test line_break_differential
//
// Boundaries are the comparison, not the rendered rows: two wraps can draw the
// same characters over different source offsets, and the offsets are what the
// caret, the selection and the accessibility layer are made of. Page-level
// pagination is deliberately not compared — the editor is fluid and unpaginated
// for 1.0, and that difference is the contract's, not a divergence.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:slugline/core/document_core.dart';
import 'package:slugline/editor/line_layout.dart';
import 'package:slugline/editor/metrics.dart';

void main() {
  final cases = _load();

  test('the fixture covers the corpus it claims to', () {
    // A fixture that failed to load, or one truncated to a handful of cases,
    // would let every test below pass without asking anything.
    expect(cases.length, greaterThan(900));
    for (final file in const [
      '01-minimal',
      '02-every-element',
      '03-dual-dialogue',
      '04-notes-and-boneyard',
      '05-title-page',
      '06-crlf',
      '07-bom',
      '08-non-ascii',
      '09-whitespace',
      '10-malformed',
    ]) {
      expect(cases.any((c) => c.name.startsWith('$file#')), isTrue,
          reason: '$file contributed no block to the fixture');
    }
    expect(cases.where((c) => c.name.startsWith('reference-feature#')).length,
        greaterThan(500));
    expect(cases.where((c) => c.uppercase).isNotEmpty, isTrue);
  });

  test('generated edge cases wrap identically', () {
    _compare(cases.where((c) => c.name.startsWith('edge/')));
  });

  test('display casing is the same scalar for scalar', () {
    // Phase 6B left the contract's uppercase rule resting on Dart's
    // `toUpperCase` and Rust's `char::to_uppercase` agreeing scalar by scalar.
    // The sweeps are whole Unicode blocks, so a table update that moved one of
    // them apart would fail here rather than silently move a wrap in a heading.
    _compare(cases.where((c) => c.name.startsWith('sweep/')));
  });

  test('every block of every corpus file wraps identically', () {
    _compare(cases.where((c) =>
        !c.name.startsWith('edge/') &&
        !c.name.startsWith('sweep/') &&
        !c.name.startsWith('reference-feature#')));
  });

  test('every block of the reference feature wraps identically', () {
    _compare(cases.where((c) => c.name.startsWith('reference-feature#')));
  });
}

/// Wraps every case with `wrapText` and fails on the first disagreement, with
/// enough of both answers to see what moved.
void _compare(Iterable<_Case> cases) {
  final failures = <String>[];
  var compared = 0;
  for (final testCase in cases) {
    // The prepared text both wrappers are given. Rust applied `display_text`
    // when it built the fixture; the editor applies `displayText`, and the two
    // have to agree before a wrap can be compared at all.
    final kind = testCase.uppercase ? BlockKind.sceneHeading : BlockKind.action;
    final display = displayText(kind, testCase.text);
    final casing = _casingDifference(testCase.text, testCase.display, display);
    if (casing != null) {
      failures.add('${testCase.name}: $casing\n'
          '  source: ${_escape(testCase.text)}\n'
          '    rust: ${_escape(testCase.display)}\n'
          '    dart: ${_escape(display)}');
      continue;
    }

    final scalarAt = _scalarIndices(display);
    for (final run in testCase.runs) {
      compared++;
      final rows = wrapText(display, run.width);
      final actual = <List<int?>>[];
      var addressable = true;
      for (final row in rows) {
        final start = scalarAt[row.start];
        final end = scalarAt[row.end];
        final hard = row.hardBreakOffsetUtf16 == null
            ? null
            : scalarAt[row.hardBreakOffsetUtf16!];
        if (start == null ||
            end == null ||
            (row.hardBreakOffsetUtf16 != null && hard == null)) {
          // A boundary inside a surrogate pair is not an offset the bridge
          // would accept (ADR 0001), so it cannot be compared: it is already
          // wrong.
          failures.add('${testCase.name} at width ${run.width}: '
              'a row boundary lands inside a scalar\n'
              '  source: ${_escape(testCase.text)}\n'
              '    dart: ${_rows(_utf16Rows(rows))}');
          addressable = false;
          break;
        }
        actual.add([start, end, row.columns, hard]);
      }
      if (!addressable) continue;
      if (!_same(actual, run.lines)) {
        failures.add(_report(testCase, run, actual));
      }
    }
    if (failures.length >= 3) break;
  }

  expect(compared, greaterThan(0), reason: 'no case was compared');
  if (failures.isNotEmpty) {
    fail('${failures.length} line-breaking divergence(s) from '
        'testdata/line-breaking.json:\n\n${failures.join('\n\n')}');
  }
}

/// The last scalar whose capital both implementations must agree on.
///
/// ASCII, Latin-1 and Latin Extended-A: the alphabet an English screenplay is
/// written in, plus every accented name, loan word and European spelling one
/// plausibly carries. Inside this range a casing disagreement is a bug, because
/// it is text a writer will actually type.
///
/// Past it, Slugline promises the wrap, not the glyph. Dart's
/// `String.toUpperCase` and Rust's `char::to_uppercase` are the same rule over
/// different vintages of the same tables, and today they part company on `ƛ`
/// (U+019B), `ȿ` (U+023F), `ɀ` (U+0240) and `ϳ` (U+03F3): Rust capitalises them
/// and the Dart SDK leaves them as typed. Each is one scalar either way, so no
/// column and no boundary moves, and the wrap is still compared below — which
/// is the part this contract is about. Failing CI over a fifth such character
/// on some future SDK bump would cost maintenance for a guarantee nobody made.
///
/// `ß`, `ŉ` and `ǰ` are a different thing entirely: both languages decline those
/// on purpose, because their capital is more than one scalar.
const int _casingGuaranteedThrough = 0x017F;

/// How the editor's display casing differs from the paginator's, or null when
/// it differs only where no promise was made.
String? _casingDifference(String source, String rust, String dart) {
  if (rust == dart) return null;
  final typed = source.runes.toList();
  final left = rust.runes.toList();
  final right = dart.runes.toList();
  if (left.length != right.length || left.length != typed.length) {
    // One side changed the number of scalars, which moves every boundary after
    // it. That is the divergence the per-scalar rule exists to prevent, and it
    // is a failure at any code point.
    return 'display casing changes the scalar count '
        '(source ${typed.length}, rust ${left.length}, dart ${right.length})';
  }
  for (var scalar = 0; scalar < left.length; scalar++) {
    if (left[scalar] == right[scalar]) continue;
    final where = 'at scalar $scalar (${_codePoint(typed[scalar])}: '
        'rust ${_codePoint(left[scalar])}, dart ${_codePoint(right[scalar])})';
    if (typed[scalar] <= _casingGuaranteedThrough) {
      return 'display casing differs $where';
    }
    if (_utf16Length(left[scalar]) != _utf16Length(right[scalar])) {
      // Outside the guaranteed range the glyph may differ, but not its width:
      // one side is two code units and the other one, so every editor offset
      // after it moves.
      return 'display casing changes an offset $where';
    }
  }
  return null;
}

int _utf16Length(int scalar) => scalar > 0xFFFF ? 2 : 1;

String _codePoint(int scalar) =>
    'U+${scalar.toRadixString(16).toUpperCase().padLeft(4, '0')}';

String _report(_Case testCase, _Run run, List<List<int?>> actual) {
  final buffer = StringBuffer()
    ..writeln('${testCase.name} at width ${run.width}')
    ..writeln('  source: ${_escape(testCase.text)}')
    ..writeln('    rust: ${_rows(run.lines)}')
    ..writeln('    dart: ${_rows(actual)}');
  final shared = run.lines.length < actual.length ? run.lines.length : actual.length;
  for (var row = 0; row < shared; row++) {
    if (!_sameRow(actual[row], run.lines[row])) {
      buffer.writeln('  first mismatch at row $row: '
          'rust ${_row(run.lines[row])}, dart ${_row(actual[row])}');
      return buffer.toString().trimRight();
    }
  }
  buffer.writeln('  first mismatch at row $shared: '
      'rust has ${run.lines.length} rows, dart has ${actual.length}');
  return buffer.toString().trimRight();
}

bool _same(List<List<int?>> left, List<List<int?>> right) {
  if (left.length != right.length) return false;
  for (var row = 0; row < left.length; row++) {
    if (!_sameRow(left[row], right[row])) return false;
  }
  return true;
}

bool _sameRow(List<int?> left, List<int?> right) =>
    left[0] == right[0] &&
    left[1] == right[1] &&
    left[2] == right[2] &&
    left[3] == right[3];

/// `[start, end, columns, hard break]`, the fixture's own shape.
String _row(List<int?> row) =>
    '[${row[0]},${row[1]},${row[2]},${row[3] ?? '-'}]';

String _rows(List<List<int?>> rows) => rows.map(_row).join(' ');

List<List<int?>> _utf16Rows(List<VisualLine> rows) => [
      for (final row in rows)
        [row.start, row.end, row.columns, row.hardBreakOffsetUtf16],
    ];

/// UTF-16 offset to Unicode-scalar index, for every boundary in the string.
///
/// The editor counts code units and Rust counts bytes, so neither side's native
/// offsets are the ones in the fixture. A code unit inside a surrogate pair has
/// no scalar index and answers null, which is itself a failure.
List<int?> _scalarIndices(String text) {
  final indices = List<int?>.filled(text.length + 1, null);
  final runes = text.runes.iterator;
  var scalar = 0;
  while (runes.moveNext()) {
    indices[runes.rawIndex] = scalar++;
  }
  indices[text.length] = scalar;
  return indices;
}

String _escape(String text) {
  final buffer = StringBuffer('"');
  for (final unit in text.runes) {
    switch (unit) {
      case 0x0a:
        buffer.write(r'\n');
      case 0x09:
        buffer.write(r'\t');
      case 0x0d:
        buffer.write(r'\r');
      case 0x5c:
        buffer.write(r'\\');
      case 0x22:
        buffer.write(r'\"');
      default:
        if (unit < 0x20) {
          buffer.write('\\u${unit.toRadixString(16).padLeft(4, '0')}');
        } else {
          buffer.writeCharCode(unit);
        }
    }
  }
  return (buffer..write('"')).toString();
}

class _Case {
  _Case(this.name, this.text, this.display, this.uppercase, this.runs);

  final String name;

  /// The block text, as a writer typed it.
  final String text;

  /// [text] after Rust's display casing — what both sides actually wrap.
  final String display;

  final bool uppercase;
  final List<_Run> runs;
}

class _Run {
  _Run(this.width, this.lines);

  final int width;

  /// `[start, end, columns, hard break]` per row, in scalar indices.
  final List<List<int?>> lines;
}

List<_Case> _load() {
  final file = _fixture();
  final decoded = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  return [
    for (final entry in decoded['cases'] as List<dynamic>)
      _case(entry as Map<String, dynamic>),
  ];
}

_Case _case(Map<String, dynamic> entry) {
  final text = entry['text'] as String;
  return _Case(
    entry['name'] as String,
    text,
    entry['display'] as String? ?? text,
    entry['uppercase'] as bool,
    [
      for (final run in entry['runs'] as List<dynamic>)
        _run(run as Map<String, dynamic>),
    ],
  );
}

_Run _run(Map<String, dynamic> run) => _Run(
      run['width'] as int,
      [
        for (final line in run['lines'] as List<dynamic>)
          [
            for (final value in line as List<dynamic>) value as int?,
          ],
      ],
    );

/// The fixture, found by walking up from wherever the test runner started.
File _fixture() {
  var directory = Directory.current.absolute;
  while (true) {
    final candidate =
        File('${directory.path}/testdata/line-breaking.json');
    if (candidate.existsSync()) return candidate;
    final parent = directory.parent;
    if (parent.path == directory.path) {
      throw StateError(
        'testdata/line-breaking.json was not found above ${Directory.current.path}. '
        'Generate it with: UPDATE_LINE_BREAK_FIXTURES=1 cargo test -p slugline_layout '
        '--test line_break_differential',
      );
    }
    directory = parent;
  }
}
