// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'doc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `adopt`, `clamp_u32`, `completion_context`, `completion_kind`, `enter`, `entity_kind_name`, `finish`, `inferring`, `journal`, `kind_view`, `match_view`, `model_entity_kind`, `model_kind`, `model_new_block`, `model_query`, `no_such_document`, `ordered`, `outcome_with_title_page`, `outcome`, `paste`, `plain_blocks`, `position_view`, `refresh_entities`, `rejected`, `rejection_of`, `result_view`, `selection_view`, `step`, `tab_target`, `to_model_command`, `to_model_position`, `to_model_selection`, `view_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A new, empty script.
///
/// Phase 2 has no persistence: a document lives in memory until [`doc_close`] or
/// process exit. `library_open`/`library_create` (§6) arrive with `storage` in
/// Phase 4 and take over this job.
DocumentHandle docNew() => RustLib.instance.api.crateApiDocDocNew();

/// Parses Fountain source into a new document. Total: every input parses.
DocumentHandle docParse({required String source}) =>
    RustLib.instance.api.crateApiDocDocParse(source: source);

void docClose({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocClose(handle: handle);

int docBlockCount({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocBlockCount(handle: handle);

/// Blocks `from..to`, clamped to the document. Out-of-range asks are answered
/// with what exists, because the caller is a scrolling viewport racing an edit.
List<BlockView> docBlocks({
  required DocumentHandle handle,
  required int from,
  required int to,
}) => RustLib.instance.api.crateApiDocDocBlocks(
  handle: handle,
  from: from,
  to: to,
);

/// Scene and character navigation data (§Phase 8).
///
/// A feature-length script is only a few thousand blocks. This is a read-only
/// actor visit over those blocks, and character recognition comes from the
/// session's incrementally maintained entity index rather than a second scan.
NavigatorView docNavigator({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocNavigator(handle: handle);

/// The document as Fountain.
///
/// Phase 2 saves nothing, so this exists to let a test assert what the core
/// actually holds. Phase 4's `doc_save` writes the same bytes through `storage`.
String docSource({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocSource(handle: handle);

/// The title page, in the order a save would write it (§6's `doc_title_page`).
///
/// Canonical order, not written order: this is what the Phase 7 editor shows
/// and what the paginator lays out, and both want Title first.
List<TitleEntryView> docTitlePage({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocTitlePage(handle: handle);

/// Sets one title-page field. An empty `value` removes it.
///
/// One field per call, and one undo step per call, because that is how the
/// Phase 7 title-page editor is used: a writer fills in a form, and the
/// undo they expect is of the field they just changed. `key` is matched
/// case-insensitively against the keys the format names and kept verbatim
/// otherwise, so `draft date` and `Draft Date` are the same field and
/// `Revision Colour` is a new one.
///
/// Setting a field to what it already holds changes nothing and records
/// nothing — a form that rebuilds itself on every keystroke must not be able to
/// fill the undo stack with edits that did not happen.
EditOutcome docSetTitleField({
  required DocumentHandle handle,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiDocDocSetTitleField(
  handle: handle,
  key: key,
  value: value,
);

/// The Fountain text between two positions, for the clipboard. `None` when
/// either position does not resolve.
String? docExtract({
  required DocumentHandle handle,
  required DocPosition from,
  required DocPosition to,
}) => RustLib.instance.api.crateApiDocDocExtract(
  handle: handle,
  from: from,
  to: to,
);

/// Every match of `query`, in document order (§6's `find`).
///
/// The whole list, not a page of it: the find bar shows a live count, and a
/// count of "the first fifty" is not a count. A feature-length script is a few
/// hundred kilobytes, so this is a scan of less text than one screenshot.
List<FindMatch> docFind({
  required DocumentHandle handle,
  required FindQuery query,
}) => RustLib.instance.api.crateApiDocDocFind(handle: handle, query: query);

/// The element type Tab would move the caret's block to, without moving it.
///
/// The element bar shows this, so that "Tab" on screen means something specific
/// rather than being a key the writer has to try. It answers from the same table
/// [`doc_tab`] acts on — there is no second copy of it in Dart (§2.1).
BlockKind? docTabTarget({
  required DocumentHandle handle,
  required int block,
  required bool shift,
}) => RustLib.instance.api.crateApiDocDocTabTarget(
  handle: handle,
  block: block,
  shift: shift,
);

/// The character cue this block's text already names, if the script has one.
///
/// §Phase 3's "typing an existing character name in an Action-position block
/// suggests Character". A suggestion and nothing else: the editor shows the name
/// beside the element bar, and Tab is what accepts it.
String? docCharacterSuggestion({
  required DocumentHandle handle,
  required int block,
}) => RustLib.instance.api.crateApiDocDocCharacterSuggestion(
  handle: handle,
  block: block,
);

/// Ranked completions at a caret. This function is read-only: accepting a
/// candidate is a separate `doc_apply` call made only by Tab or Enter in Dart.
List<Completion> docComplete({
  required DocumentHandle handle,
  required int block,
  required int offsetUtf16,
  required List<String> suppressed,
}) => RustLib.instance.api.crateApiDocDocComplete(
  handle: handle,
  block: block,
  offsetUtf16: offsetUtf16,
  suppressed: suppressed,
);

/// Pins or unpins a candidate in the script's library entry. Unsaved scripts
/// keep the pin for this session and gain persistence once they have an entry.
bool docSetEntityPinned({
  required DocumentHandle handle,
  required CompletionKind kind,
  required String value,
  required bool pinned,
}) => RustLib.instance.api.crateApiDocDocSetEntityPinned(
  handle: handle,
  kind: kind,
  value: value,
  pinned: pinned,
);

/// Applies one command.
///
/// `before` is the selection the user had **before** the edit, so undo can put
/// the caret back where it was rather than where the edit left it (§3.4). Dart
/// owns the caret, so only Dart can say.
EditOutcome docApply({
  required DocumentHandle handle,
  required EditCommand command,
  DocSelection? before,
}) => RustLib.instance.api.crateApiDocDocApply(
  handle: handle,
  command: command,
  before: before,
);

/// Enter, with §Phase 3's table applied to whatever it creates.
///
/// Composed here rather than in `document` for ADR 0010's reason: the bridge
/// writes the plan, the document groups it, and one keystroke is therefore one
/// undo step even though it may be a delete, a split and a kind change. The
/// table itself is `document`'s — Dart never decides what follows an element.
EditOutcome docEnter({
  required DocumentHandle handle,
  required DocSelection at,
}) => RustLib.instance.api.crateApiDocDocEnter(handle: handle, at: at);

/// Tab, or Shift+Tab, on the block the caret is in.
///
/// `None` — not a rejection — where the table says Tab does nothing. There is
/// nothing to report and nothing to beep about: the writer pressed a key that
/// means "next element type" in a place that has no next element type, and the
/// editor's answer is to leave the document exactly as it was.
EditOutcome? docTab({
  required DocumentHandle handle,
  required DocSelection at,
  required bool shift,
}) => RustLib.instance.api.crateApiDocDocTab(
  handle: handle,
  at: at,
  shift: shift,
);

/// Replaces every match of `query` with `with`, as one undo transaction.
EditOutcome docReplaceAll({
  required DocumentHandle handle,
  required FindQuery query,
  required String with_,
}) => RustLib.instance.api.crateApiDocDocReplaceAll(
  handle: handle,
  query: query,
  with_: with_,
);

/// Inserts `text` at `at`, replacing the selection if there is one, as **one**
/// undo transaction.
///
/// `plain` is `Ctrl+Shift+V` (§Phase 2): the text becomes Action blocks and no
/// element is inferred from it. Otherwise the text is parsed as Fountain, and
/// the blocks it produces keep their own kinds.
EditOutcome docPaste({
  required DocumentHandle handle,
  required DocSelection at,
  required String text,
  required bool plain,
}) => RustLib.instance.api.crateApiDocDocPaste(
  handle: handle,
  at: at,
  text: text,
  plain: plain,
);

EditResult? docUndo({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocUndo(handle: handle);

EditResult? docRedo({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocRedo(handle: handle);

/// The element types of §3.1.
///
/// Flat on purpose. `BlockKind::Section` carries a level in the model, and an
/// enum with a payload becomes a `freezed` union in Dart — which the editor
/// would then have to destructure on every block it paints, and which cannot be
/// a map key. The level rides alongside in [`BlockView::section_level`] instead.
/// See ADR 0009.
enum BlockKind {
  sceneHeading,
  action,
  character,
  dialogue,
  parenthetical,
  transition,
  centered,
  lyric,
  section,
  synopsis,
  note,
  pageBreak,

  /// Valid Fountain the editor does not model. Round-trips verbatim and
  /// refuses every edit (§3.2).
  opaque,
}

/// One block, as the editor needs it.
class BlockView {
  /// `BlockId` (§3.1). Stable for the life of the document, never reused, and
  /// the key Flutter builds its list against.
  final int id;
  final BlockKind kind;

  /// 1–6 when `kind` is `Section`, 0 otherwise.
  final int sectionLevel;

  /// The user-visible text, with Fountain emphasis markup retained inline.
  final String text;
  final bool forced;
  final bool dual;

  /// The block cannot be edited. Only `Opaque` blocks are.
  final bool readOnly;

  const BlockView({
    required this.id,
    required this.kind,
    required this.sectionLevel,
    required this.text,
    required this.forced,
    required this.dual,
    required this.readOnly,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      sectionLevel.hashCode ^
      text.hashCode ^
      forced.hashCode ^
      dual.hashCode ^
      readOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          sectionLevel == other.sectionLevel &&
          text == other.text &&
          forced == other.forced &&
          dual == other.dual &&
          readOnly == other.readOnly;
}

/// One ranked §7 candidate and the exact range an explicit acceptance replaces.
class Completion {
  final CompletionKind kind;
  final String value;
  final int startUtf16;
  final int endUtf16;
  final int frequency;
  final bool pinned;

  const Completion({
    required this.kind,
    required this.value,
    required this.startUtf16,
    required this.endUtf16,
    required this.frequency,
    required this.pinned,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      value.hashCode ^
      startUtf16.hashCode ^
      endUtf16.hashCode ^
      frequency.hashCode ^
      pinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Completion &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16 &&
          frequency == other.frequency &&
          pinned == other.pinned;
}

enum CompletionKind { character, location, scenePrefix, timeOfDay, transition }

/// A caret position, in document coordinates (§3.3).
class DocPosition {
  final int block;
  final int offsetUtf16;

  const DocPosition({required this.block, required this.offsetUtf16});

  @override
  int get hashCode => block.hashCode ^ offsetUtf16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocPosition &&
          runtimeType == other.runtimeType &&
          block == other.block &&
          offsetUtf16 == other.offsetUtf16;
}

/// A selection, which may be empty (a caret) and may run in either direction.
class DocSelection {
  final DocPosition anchor;
  final DocPosition focus;

  const DocSelection({required this.anchor, required this.focus});

  @override
  int get hashCode => anchor.hashCode ^ focus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocSelection &&
          runtimeType == other.runtimeType &&
          anchor == other.anchor &&
          focus == other.focus;
}

/// A document open in the core. Dart holds one of these for the lifetime of an
/// editor; it is not a pointer, so a stale one is refused rather than followed.
class DocumentHandle {
  final int id;

  const DocumentHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

@freezed
sealed class EditCommand with _$EditCommand {
  const EditCommand._();

  const factory EditCommand.replaceText({
    required int block,
    required int startUtf16,
    required int endUtf16,
    required String with_,
  }) = EditCommand_ReplaceText;
  const factory EditCommand.splitBlock({
    required int block,
    required int atUtf16,
  }) = EditCommand_SplitBlock;

  /// Merges `first` with the block that follows it.
  const factory EditCommand.mergeBlocks({required int first}) =
      EditCommand_MergeBlocks;
  const factory EditCommand.setKind({
    required int block,
    required BlockKind kind,
    required int sectionLevel,
    required bool forced,
  }) = EditCommand_SetKind;
  const factory EditCommand.insertBlocks({
    int? after,
    required List<NewBlock> blocks,
  }) = EditCommand_InsertBlocks;
  const factory EditCommand.deleteRange({
    required DocPosition from,
    required DocPosition to,
  }) = EditCommand_DeleteRange;
  const factory EditCommand.setDual({required int block, required bool dual}) =
      EditCommand_SetDual;
}

@freezed
sealed class EditOutcome with _$EditOutcome {
  const EditOutcome._();

  const factory EditOutcome.applied({required EditResult result}) =
      EditOutcome_Applied;
  const factory EditOutcome.rejected({
    required EditRejection reason,

    /// Human-readable, for the log and for test failures. Not for the UI.
    required String message,
  }) = EditOutcome_Rejected;
}

/// Why an edit did not apply.
///
/// A rejection is a value rather than an exception because two of these are
/// ordinary user actions, not bugs: typing inside a boneyard comment, and
/// backspacing at the very start of the script. Flutter beeps; it does not catch.
enum EditRejection {
  /// No block with that id — it was deleted, or the handle is stale.
  unknownBlock,

  /// Past the end of a block, or inside a character.
  badOffset,

  /// The command needs a block after this one and there is none.
  noBlockAfter,
  badRange,

  /// The block round-trips verbatim and cannot be edited (§3.2).
  notEditable,

  /// The command would leave a block in a state the model cannot represent.
  invalidBlock,

  /// A UTF-16 offset that lands between the halves of a surrogate pair, or
  /// past the end of the text (ADR 0001). Nothing is rounded.
  badUtf16Offset,

  /// No document with that handle.
  noSuchDocument,
}

/// What an edit did, as a patch Flutter applies to its own copy (§6).
class EditResult {
  final List<BlockView> changed;
  final List<int> removed;
  final List<InsertedBlock> inserted;

  /// The caret after the edit. `None` when there is no block to anchor it to.
  final DocSelection? selection;

  /// Blocks in the document afterwards, so Dart can assert its copy is right
  /// rather than assume it.
  final int blockCount;

  const EditResult({
    required this.changed,
    required this.removed,
    required this.inserted,
    this.selection,
    required this.blockCount,
  });

  @override
  int get hashCode =>
      changed.hashCode ^
      removed.hashCode ^
      inserted.hashCode ^
      selection.hashCode ^
      blockCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditResult &&
          runtimeType == other.runtimeType &&
          changed == other.changed &&
          removed == other.removed &&
          inserted == other.inserted &&
          selection == other.selection &&
          blockCount == other.blockCount;
}

/// One hit (§6's `Match`).
class FindMatch {
  final int block;
  final int startUtf16;
  final int endUtf16;

  const FindMatch({
    required this.block,
    required this.startUtf16,
    required this.endUtf16,
  });

  @override
  int get hashCode => block.hashCode ^ startUtf16.hashCode ^ endUtf16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FindMatch &&
          runtimeType == other.runtimeType &&
          block == other.block &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16;
}

/// What to look for (§6's `FindQuery`).
class FindQuery {
  final String text;
  final bool caseSensitive;
  final bool wholeWord;

  /// When empty, every block is searched. Otherwise only these kinds are —
  /// §Phase 3's optional element filter. A `Section` here matches every level.
  final List<BlockKind> kinds;

  const FindQuery({
    required this.text,
    required this.caseSensitive,
    required this.wholeWord,
    required this.kinds,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      caseSensitive.hashCode ^
      wholeWord.hashCode ^
      kinds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FindQuery &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          caseSensitive == other.caseSensitive &&
          wholeWord == other.wholeWord &&
          kinds == other.kinds;
}

/// A block that appeared, and the index it appeared at.
///
/// The index is the block's position **after** the edit, so Dart can apply the
/// patch as: drop `removed`, update `changed`, then insert these in ascending
/// index order.
class InsertedBlock {
  final int index;
  final BlockView block;

  const InsertedBlock({required this.index, required this.block});

  @override
  int get hashCode => index.hashCode ^ block.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertedBlock &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          block == other.block;
}

/// One character in §Phase 8's navigator.
class NavigatorCharacter {
  final String name;
  final int occurrences;

  /// Character-cue block ids, in document order. The UI uses these for an
  /// explicit jump; reading the navigator never changes the document.
  final List<int> blocks;

  const NavigatorCharacter({
    required this.name,
    required this.occurrences,
    required this.blocks,
  });

  @override
  int get hashCode => name.hashCode ^ occurrences.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavigatorCharacter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          occurrences == other.occurrences &&
          blocks == other.blocks;
}

/// One scene in §Phase 8's navigator.
class NavigatorScene {
  final int block;
  final String? sceneNumber;
  final String prefix;
  final String location;
  final String? timeOfDay;

  const NavigatorScene({
    required this.block,
    this.sceneNumber,
    required this.prefix,
    required this.location,
    this.timeOfDay,
  });

  @override
  int get hashCode =>
      block.hashCode ^
      sceneNumber.hashCode ^
      prefix.hashCode ^
      location.hashCode ^
      timeOfDay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavigatorScene &&
          runtimeType == other.runtimeType &&
          block == other.block &&
          sceneNumber == other.sceneNumber &&
          prefix == other.prefix &&
          location == other.location &&
          timeOfDay == other.timeOfDay;
}

/// The read-only semantic snapshot behind §Phase 8's navigator.
class NavigatorView {
  final List<NavigatorScene> scenes;
  final List<NavigatorCharacter> characters;

  const NavigatorView({required this.scenes, required this.characters});

  @override
  int get hashCode => scenes.hashCode ^ characters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavigatorView &&
          runtimeType == other.runtimeType &&
          scenes == other.scenes &&
          characters == other.characters;
}

/// A block to be inserted, before the document has given it an identity.
class NewBlock {
  final BlockKind kind;
  final int sectionLevel;
  final String text;
  final bool forced;
  final bool dual;

  const NewBlock({
    required this.kind,
    required this.sectionLevel,
    required this.text,
    required this.forced,
    required this.dual,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sectionLevel.hashCode ^
      text.hashCode ^
      forced.hashCode ^
      dual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewBlock &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sectionLevel == other.sectionLevel &&
          text == other.text &&
          forced == other.forced &&
          dual == other.dual;
}

/// One `Key: value` pair of the title page (§6's `TitlePage`).
///
/// A key and a string, rather than an enumeration of the fields §Phase 7 names.
/// The format allows any key and the parser keeps the spelling of one it does
/// not recognise (`TitleField::Other`), so a surface that could only say
/// "Title" or "Credit" would be a surface that quietly dropped a writer's
/// `Revision Colour:` the first time they edited anything.
class TitleEntryView {
  /// As it will be written back to the file.
  final String key;

  /// Multi-line values keep their `\n`, whatever the file's line ending is.
  final String value;

  const TitleEntryView({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TitleEntryView &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}
