// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'doc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `adopt`, `clamp_u32`, `kind_view`, `model_kind`, `model_new_block`, `no_such_document`, `ordered`, `outcome`, `paste`, `plain_blocks`, `position_view`, `rejected`, `rejection_of`, `result_view`, `selection_view`, `step`, `to_model_command`, `to_model_position`, `to_model_selection`, `view_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A new, empty script.
///
/// Phase 2 has no persistence: a document lives in memory until [`doc_close`] or
/// process exit. `library_open`/`library_create` (§6) arrive with `storage` in
/// Phase 4 and take over this job.
DocumentHandle docNew() => RustLib.instance.api.crateApiDocDocNew();

/// Parses Fountain source into a new document. Total: every input parses.
DocumentHandle docParse({required String source}) =>
    RustLib.instance.api.crateApiDocDocParse(source: source);

void docClose({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocClose(handle: handle);

int docBlockCount({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocBlockCount(handle: handle);

/// Blocks `from..to`, clamped to the document. Out-of-range asks are answered
/// with what exists, because the caller is a scrolling viewport racing an edit.
List<BlockView> docBlocks({
  required DocumentHandle handle,
  required int from,
  required int to,
}) => RustLib.instance.api.crateApiDocDocBlocks(
  handle: handle,
  from: from,
  to: to,
);

/// The document as Fountain.
///
/// Phase 2 saves nothing, so this exists to let a test assert what the core
/// actually holds. Phase 4's `doc_save` writes the same bytes through `storage`.
String docSource({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocSource(handle: handle);

/// The Fountain text between two positions, for the clipboard. `None` when
/// either position does not resolve.
String? docExtract({
  required DocumentHandle handle,
  required DocPosition from,
  required DocPosition to,
}) => RustLib.instance.api.crateApiDocDocExtract(
  handle: handle,
  from: from,
  to: to,
);

/// Applies one command.
///
/// `before` is the selection the user had **before** the edit, so undo can put
/// the caret back where it was rather than where the edit left it (§3.4). Dart
/// owns the caret, so only Dart can say.
EditOutcome docApply({
  required DocumentHandle handle,
  required EditCommand command,
  DocSelection? before,
}) => RustLib.instance.api.crateApiDocDocApply(
  handle: handle,
  command: command,
  before: before,
);

/// Inserts `text` at `at`, replacing the selection if there is one, as **one**
/// undo transaction.
///
/// `plain` is `Ctrl+Shift+V` (§Phase 2): the text becomes Action blocks and no
/// element is inferred from it. Otherwise the text is parsed as Fountain, and
/// the blocks it produces keep their own kinds.
EditOutcome docPaste({
  required DocumentHandle handle,
  required DocSelection at,
  required String text,
  required bool plain,
}) => RustLib.instance.api.crateApiDocDocPaste(
  handle: handle,
  at: at,
  text: text,
  plain: plain,
);

EditResult? docUndo({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocUndo(handle: handle);

EditResult? docRedo({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiDocDocRedo(handle: handle);

/// The element types of §3.1.
///
/// Flat on purpose. `BlockKind::Section` carries a level in the model, and an
/// enum with a payload becomes a `freezed` union in Dart — which the editor
/// would then have to destructure on every block it paints, and which cannot be
/// a map key. The level rides alongside in [`BlockView::section_level`] instead.
/// See ADR 0009.
enum BlockKind {
  sceneHeading,
  action,
  character,
  dialogue,
  parenthetical,
  transition,
  centered,
  lyric,
  section,
  synopsis,
  note,
  pageBreak,

  /// Valid Fountain the editor does not model. Round-trips verbatim and
  /// refuses every edit (§3.2).
  opaque,
}

/// One block, as the editor needs it.
class BlockView {
  /// `BlockId` (§3.1). Stable for the life of the document, never reused, and
  /// the key Flutter builds its list against.
  final int id;
  final BlockKind kind;

  /// 1–6 when `kind` is `Section`, 0 otherwise.
  final int sectionLevel;

  /// The user-visible text, with Fountain emphasis markup retained inline.
  final String text;
  final bool forced;
  final bool dual;

  /// The block cannot be edited. Only `Opaque` blocks are.
  final bool readOnly;

  const BlockView({
    required this.id,
    required this.kind,
    required this.sectionLevel,
    required this.text,
    required this.forced,
    required this.dual,
    required this.readOnly,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      sectionLevel.hashCode ^
      text.hashCode ^
      forced.hashCode ^
      dual.hashCode ^
      readOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          sectionLevel == other.sectionLevel &&
          text == other.text &&
          forced == other.forced &&
          dual == other.dual &&
          readOnly == other.readOnly;
}

/// A caret position, in document coordinates (§3.3).
class DocPosition {
  final int block;
  final int offsetUtf16;

  const DocPosition({required this.block, required this.offsetUtf16});

  @override
  int get hashCode => block.hashCode ^ offsetUtf16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocPosition &&
          runtimeType == other.runtimeType &&
          block == other.block &&
          offsetUtf16 == other.offsetUtf16;
}

/// A selection, which may be empty (a caret) and may run in either direction.
class DocSelection {
  final DocPosition anchor;
  final DocPosition focus;

  const DocSelection({required this.anchor, required this.focus});

  @override
  int get hashCode => anchor.hashCode ^ focus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocSelection &&
          runtimeType == other.runtimeType &&
          anchor == other.anchor &&
          focus == other.focus;
}

/// A document open in the core. Dart holds one of these for the lifetime of an
/// editor; it is not a pointer, so a stale one is refused rather than followed.
class DocumentHandle {
  final int id;

  const DocumentHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

@freezed
sealed class EditCommand with _$EditCommand {
  const EditCommand._();

  const factory EditCommand.replaceText({
    required int block,
    required int startUtf16,
    required int endUtf16,
    required String with_,
  }) = EditCommand_ReplaceText;
  const factory EditCommand.splitBlock({
    required int block,
    required int atUtf16,
  }) = EditCommand_SplitBlock;

  /// Merges `first` with the block that follows it.
  const factory EditCommand.mergeBlocks({required int first}) =
      EditCommand_MergeBlocks;
  const factory EditCommand.setKind({
    required int block,
    required BlockKind kind,
    required int sectionLevel,
    required bool forced,
  }) = EditCommand_SetKind;
  const factory EditCommand.insertBlocks({
    int? after,
    required List<NewBlock> blocks,
  }) = EditCommand_InsertBlocks;
  const factory EditCommand.deleteRange({
    required DocPosition from,
    required DocPosition to,
  }) = EditCommand_DeleteRange;
  const factory EditCommand.setDual({required int block, required bool dual}) =
      EditCommand_SetDual;
}

@freezed
sealed class EditOutcome with _$EditOutcome {
  const EditOutcome._();

  const factory EditOutcome.applied({required EditResult result}) =
      EditOutcome_Applied;
  const factory EditOutcome.rejected({
    required EditRejection reason,

    /// Human-readable, for the log and for test failures. Not for the UI.
    required String message,
  }) = EditOutcome_Rejected;
}

/// Why an edit did not apply.
///
/// A rejection is a value rather than an exception because two of these are
/// ordinary user actions, not bugs: typing inside a boneyard comment, and
/// backspacing at the very start of the script. Flutter beeps; it does not catch.
enum EditRejection {
  /// No block with that id — it was deleted, or the handle is stale.
  unknownBlock,

  /// Past the end of a block, or inside a character.
  badOffset,

  /// The command needs a block after this one and there is none.
  noBlockAfter,
  badRange,

  /// The block round-trips verbatim and cannot be edited (§3.2).
  notEditable,

  /// The command would leave a block in a state the model cannot represent.
  invalidBlock,

  /// A UTF-16 offset that lands between the halves of a surrogate pair, or
  /// past the end of the text (ADR 0001). Nothing is rounded.
  badUtf16Offset,

  /// No document with that handle.
  noSuchDocument,
}

/// What an edit did, as a patch Flutter applies to its own copy (§6).
class EditResult {
  final List<BlockView> changed;
  final List<int> removed;
  final List<InsertedBlock> inserted;

  /// The caret after the edit. `None` when there is no block to anchor it to.
  final DocSelection? selection;

  /// Blocks in the document afterwards, so Dart can assert its copy is right
  /// rather than assume it.
  final int blockCount;

  const EditResult({
    required this.changed,
    required this.removed,
    required this.inserted,
    this.selection,
    required this.blockCount,
  });

  @override
  int get hashCode =>
      changed.hashCode ^
      removed.hashCode ^
      inserted.hashCode ^
      selection.hashCode ^
      blockCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditResult &&
          runtimeType == other.runtimeType &&
          changed == other.changed &&
          removed == other.removed &&
          inserted == other.inserted &&
          selection == other.selection &&
          blockCount == other.blockCount;
}

/// A block that appeared, and the index it appeared at.
///
/// The index is the block's position **after** the edit, so Dart can apply the
/// patch as: drop `removed`, update `changed`, then insert these in ascending
/// index order.
class InsertedBlock {
  final int index;
  final BlockView block;

  const InsertedBlock({required this.index, required this.block});

  @override
  int get hashCode => index.hashCode ^ block.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertedBlock &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          block == other.block;
}

/// A block to be inserted, before the document has given it an identity.
class NewBlock {
  final BlockKind kind;
  final int sectionLevel;
  final String text;
  final bool forced;
  final bool dual;

  const NewBlock({
    required this.kind,
    required this.sectionLevel,
    required this.text,
    required this.forced,
    required this.dual,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sectionLevel.hashCode ^
      text.hashCode ^
      forced.hashCode ^
      dual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewBlock &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sectionLevel == other.sectionLevel &&
          text == other.text &&
          forced == other.forced &&
          dual == other.dual;
}
