// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'files.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `sink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Subscribe to the core event stream. A second subscription replaces the first,
/// which is what a Flutter hot restart does.
Stream<CoreEvent> coreEvents() =>
    RustLib.instance.api.crateApiEventsCoreEvents();

/// Push an event at Dart.
///
/// Does nothing when nobody has subscribed. Dropping a notification is always
/// better than blocking the core on the UI — and this is called from the actor
/// thread, from FRB worker threads, and from `notify`'s watcher thread, none of
/// which may wait on Dart.
Future<void> emit({required CoreEvent event}) =>
    RustLib.instance.api.crateApiEventsEmit(event: event);

@freezed
sealed class CoreEvent with _$CoreEvent {
  const CoreEvent._();

  /// A document became clean, or dirty. The title bar's asterisk.
  const factory CoreEvent.saveStateChanged({
    required int handle,
    required bool dirty,
  }) = CoreEvent_SaveStateChanged;

  /// An autosave failed. §Phase 4 requires a save failure to be explicit and
  /// blocking — but an autosave is not a save the user asked for, so this is
  /// the quieter half of that rule: it reaches the status bar, not a modal,
  /// and it says exactly what went wrong.
  const factory CoreEvent.autosaveFailed({
    required int handle,
    required SaveFailure failure,
    required String message,
  }) = CoreEvent_AutosaveFailed;

  /// A file under an open document changed on disk. Dart asks
  /// `doc_external_change` what to do about it.
  const factory CoreEvent.fileChangedOnDisk({required String path}) =
      CoreEvent_FileChangedOnDisk;

  /// A rolling backup was written.
  const factory CoreEvent.backupWritten({
    required int handle,
    required String path,
  }) = CoreEvent_BackupWritten;

  /// A successful edit changed the incrementally maintained §7 index.
  const factory CoreEvent.entityIndexUpdated({required int handle}) =
      CoreEvent_EntityIndexUpdated;

  /// The journal stopped working for this document. The writer keeps typing;
  /// what they lose is the cover between one autosave and the next.
  const factory CoreEvent.journalBroken({required int handle}) =
      CoreEvent_JournalBroken;

  /// This document's file could not be watched for external changes: no
  /// inotify, no watch descriptors left, or a filesystem that does not support
  /// it.
  ///
  /// Nothing is unsafe — the save path checks the file it is replacing whether
  /// the watcher runs or not (`watch::DiskState`) — but nobody will be told
  /// that another program wrote this script until a save asks, so the writer is
  /// told that once and the status line keeps saying it.
  const factory CoreEvent.externalWatchUnavailable({required int handle}) =
      CoreEvent_ExternalWatchUnavailable;
}
