// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'doc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'files.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `degraded`, `failed`, `failure_of`, `hydrate_pins`, `open_source`, `prefs_view`, `rebind`, `restart_journal`, `save_library`, `script_view`, `unused_path`, `watch`, `write_document`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Plan`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// §6's `init`. Tells the core where its directories are and reads what is in
/// them.
///
/// Async because it touches the disk: it reads the preferences and the library
/// index, and starts the file watcher.
///
/// Empty strings mean "work it out from XDG", which is what the application
/// passes. A test passes three temporary directories and gets a core that
/// cannot see the real ones.
Future<bool> init({
  required String configDir,
  required String dataDir,
  required String stateDir,
}) => RustLib.instance.api.crateApiFilesInit(
  configDir: configDir,
  dataDir: dataDir,
  stateDir: stateDir,
);

/// Ends the session cleanly: every journal is discarded and the library index is
/// written.
///
/// Dart calls this from the window's close handler. If it never runs — because
/// the process was killed — the journals stay on disk and the next startup finds
/// them, which is exactly the behaviour they exist for.
Future<void> shutdown() => RustLib.instance.api.crateApiFilesShutdown();

/// §6's `library_list`.
Future<List<ScriptView>> libraryList() =>
    RustLib.instance.api.crateApiFilesLibraryList();

/// §6's `library_open`. Reads the file and hands back a document.
///
/// Opening a file that is already open returns the handle it is already open
/// under. Two documents over one file would be two undo histories racing to
/// overwrite each other.
Future<DocumentHandle?> libraryOpen({required String path}) =>
    RustLib.instance.api.crateApiFilesLibraryOpen(path: path);

/// §6's `library_create`. A new, empty script at `path`.
///
/// The file is written immediately, and the handle only comes back if it was:
/// "create" that leaves nothing on disk is a promise the library index would
/// then be holding a broken pointer to.
Future<DocumentHandle?> libraryCreate({required String path}) =>
    RustLib.instance.api.crateApiFilesLibraryCreate(path: path);

/// §6's `library_rename`. Moves the file and follows it.
Future<SaveOutcome> libraryRename({
  required String id,
  required String newPath,
}) => RustLib.instance.api.crateApiFilesLibraryRename(id: id, newPath: newPath);

/// §6's `library_duplicate`. Copies the file beside itself and adds the copy.
Future<ScriptView?> libraryDuplicate({required String id}) =>
    RustLib.instance.api.crateApiFilesLibraryDuplicate(id: id);

/// §6's `library_remove`. Forgets the script, and deletes the file only if asked.
///
/// The two are separate on purpose (§Phase 4 lists "remove-from-library" and
/// "delete-file" as different commands). Removing from the library is
/// reversible by opening the file again; deleting is not, which is why it is a
/// different word in the UI and a different argument here.
Future<bool> libraryRemove({required String id, required bool deleteFile}) =>
    RustLib.instance.api.crateApiFilesLibraryRemove(
      id: id,
      deleteFile: deleteFile,
    );

/// §6's `session_restore`: the scripts that were open when the application last
/// exited, with the scroll position each was at.
///
/// Returns entries rather than ids, so Dart can show the list and reopen it in
/// one pass rather than asking about each one.
Future<List<ScriptView>> sessionRestore() =>
    RustLib.instance.api.crateApiFilesSessionRestore();

/// Records where the writer is in a script, so that a crash does not lose the
/// scroll position along with everything else.
void docSetScroll({required DocumentHandle handle, required int row}) =>
    RustLib.instance.api.crateApiFilesDocSetScroll(handle: handle, row: row);

/// Whether the document has edits that are not in its file (§6's `doc_dirty`).
bool docDirty({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocDirty(handle: handle);

/// The file this document is, or `None` for one that has never been saved.
String? docPath({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocPath(handle: handle);

/// How many edits are in the journal since the last save, and whether the
/// journal is still working. The status bar shows both.
(int, bool) docJournalState({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocJournalState(handle: handle);

/// §6's `doc_save`.
Future<SaveOutcome> docSave({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocSave(handle: handle);

/// Save As, and §6's `doc_export_fountain` — the same operation.
///
/// The document follows the new path: after Save As, this *is* the file, and
/// the journal, the backups and the library entry all move with it.
Future<SaveOutcome> docSaveAs({
  required DocumentHandle handle,
  required String path,
}) => RustLib.instance.api.crateApiFilesDocSaveAs(handle: handle, path: path);

/// The autosave, called by Dart's own timers.
///
/// Identical to [`doc_save`] except that it writes no backup — a backup per
/// autosave would be a hundred a day and would push yesterday's draft out of the
/// retention window by lunchtime — and that it answers [`SaveOutcome::Unchanged`]
/// quietly when there is nothing to write, which is most of the time.
Future<SaveOutcome> docAutosave({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocAutosave(handle: handle);

/// What the file on disk says now, next to what the document says.
///
/// Dart calls this when a [`CoreEvent::FileChangedOnDisk`] names a path it has
/// open. §Phase 4: reload silently when the document is unmodified, prompt when
/// it is not — and the two facts that decision needs are exactly the two here.
(bool, bool)? docExternalChange({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocExternalChange(handle: handle);

/// "Take Theirs": throws away what is in memory and reads the file again.
///
/// The undo history goes with it. It has to: the transactions in it invert edits
/// against a document that no longer exists, and applying one would produce text
/// that was never anywhere.
Future<bool> docReload({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesDocReload(handle: handle);

/// Every rolling backup of this document, newest first.
Future<List<BackupView>> backupsList({required DocumentHandle handle}) =>
    RustLib.instance.api.crateApiFilesBackupsList(handle: handle);

/// §Phase 4's "Restore previous version".
///
/// "Restoring a backup writes the current state to a new backup first" — so this
/// saves before it restores, which means the restore is itself undoable by
/// restoring the copy it just made.
Future<SaveOutcome> backupRestore({
  required DocumentHandle handle,
  required String backupPath,
}) => RustLib.instance.api.crateApiFilesBackupRestore(
  handle: handle,
  backupPath: backupPath,
);

/// Every crashed session found at startup.
///
/// Reads the journals but applies nothing. §Phase 4 is explicit that recovery
/// "never auto-applies", and this is where that is enforced: the only thing that
/// can turn an offer into a document is the user answering the dialog.
Future<List<RecoveryOffer>> recoveryPending() =>
    RustLib.instance.api.crateApiFilesRecoveryPending();

/// Takes an offer: replays the journal and opens the result.
///
/// The document comes back **dirty**, and that is the point — the file on disk
/// is still the one from before the crash, and the writer decides whether to
/// keep what they are being shown.
///
/// ## The durability sequence
///
/// Recovery is the one moment in this program where the only durable copy of the
/// writer's text is a journal rather than a file. Everything below is arranged
/// around one rule: **that journal does not stop existing until an equivalent
/// one does.**
///
/// 1. Read and verify the old journal. Verification returns the file's real
///    bytes, which are still the pre-crash ones.
/// 2. Replay onto those bytes, remembering exactly which patches applied. A
///    patch that does not fit stops the replay, and the ones after it are not in
///    the recovered document, so they must not be in its journal either.
/// 3. Open the document and bind it to its file, library entry and watch.
/// 4. Write the **successor journal**: same `base` — the file has not changed —
///    plus the patches that replayed. [`Journal::rebuild`] writes it through the
///    atomic save, so it either exists whole or does not exist.
/// 5. Only now remove the old journal, and only if the successor did not already
///    replace it at the same path.
///
/// What this buys, and what the previous sequence did not: a second crash before
/// the writer saves or types anything recovers exactly what the first one did,
/// and a second crash *after* they type more recovers both. The old sequence
/// removed the journal at step 3 and started an empty one whose `base` was the
/// in-memory text, which matched no file — so the recovered edits existed only in
/// memory, and a journal written against them came back from [`journal::verify`]
/// as `blocked`.
///
/// Notice what is *not* here: a save. Recovery still never writes the script.
Future<RecoveryOutcome> recoveryAccept({required String journalPath}) =>
    RustLib.instance.api.crateApiFilesRecoveryAccept(journalPath: journalPath);

/// Declines an offer. The journal is deleted; the file is untouched.
Future<bool> recoveryDiscard({required String journalPath}) =>
    RustLib.instance.api.crateApiFilesRecoveryDiscard(journalPath: journalPath);

PreferencesView prefsGet() => RustLib.instance.api.crateApiFilesPrefsGet();

Future<bool> prefsSet({required PreferencesView preferences}) =>
    RustLib.instance.api.crateApiFilesPrefsSet(preferences: preferences);

/// One rolling backup (§Phase 4's "Restore previous version" list).
class BackupView {
  final String path;
  final int writtenMillis;
  final int bytes;

  const BackupView({
    required this.path,
    required this.writtenMillis,
    required this.bytes,
  });

  @override
  int get hashCode => path.hashCode ^ writtenMillis.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupView &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          writtenMillis == other.writtenMillis &&
          bytes == other.bytes;
}

/// §6's `Preferences`, as far as Phase 4 defines them.
class PreferencesView {
  final bool autosaveEnabled;
  final bool autocompleteEnabled;
  final int autosaveIdleMs;
  final int autosaveIntervalMs;
  final String? backupDir;
  final int backupKeepVersions;
  final int backupKeepDays;

  const PreferencesView({
    required this.autosaveEnabled,
    required this.autocompleteEnabled,
    required this.autosaveIdleMs,
    required this.autosaveIntervalMs,
    this.backupDir,
    required this.backupKeepVersions,
    required this.backupKeepDays,
  });

  @override
  int get hashCode =>
      autosaveEnabled.hashCode ^
      autocompleteEnabled.hashCode ^
      autosaveIdleMs.hashCode ^
      autosaveIntervalMs.hashCode ^
      backupDir.hashCode ^
      backupKeepVersions.hashCode ^
      backupKeepDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreferencesView &&
          runtimeType == other.runtimeType &&
          autosaveEnabled == other.autosaveEnabled &&
          autocompleteEnabled == other.autocompleteEnabled &&
          autosaveIdleMs == other.autosaveIdleMs &&
          autosaveIntervalMs == other.autosaveIntervalMs &&
          backupDir == other.backupDir &&
          backupKeepVersions == other.backupKeepVersions &&
          backupKeepDays == other.backupKeepDays;
}

/// A crashed session, as an offer to the user.
///
/// §Phase 4: "Recovery presents a diff summary ('14 edits since last save') and
/// Recover / Discard, never auto-applies." This is that summary; nothing has
/// been applied to anything when one of these is handed to Dart.
class RecoveryOffer {
  /// Names this offer in [`recovery_accept`] and [`recovery_discard`].
  final String journal;

  /// The script it belongs to. Empty for a script that was never saved.
  final String script;

  /// A file name, or "Untitled" — what to put in the dialog.
  final String title;

  /// The "14" in "14 edits since last save".
  final int edits;

  /// The journal's last record was incomplete, which is the ordinary shape of
  /// a crash. Worth saying, because it means the very last keystroke is gone.
  final bool damaged;

  /// Why this offer cannot be taken, if it cannot. `None` means it can.
  final String? blocked;

  const RecoveryOffer({
    required this.journal,
    required this.script,
    required this.title,
    required this.edits,
    required this.damaged,
    this.blocked,
  });

  @override
  int get hashCode =>
      journal.hashCode ^
      script.hashCode ^
      title.hashCode ^
      edits.hashCode ^
      damaged.hashCode ^
      blocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryOffer &&
          runtimeType == other.runtimeType &&
          journal == other.journal &&
          script == other.script &&
          title == other.title &&
          edits == other.edits &&
          damaged == other.damaged &&
          blocked == other.blocked;
}

@freezed
sealed class RecoveryOutcome with _$RecoveryOutcome {
  const RecoveryOutcome._();

  /// Replayed, and a journal describing the recovered edits is on disk. This
  /// is the ordinary answer.
  const factory RecoveryOutcome.recovered({required DocumentHandle handle}) =
      RecoveryOutcome_Recovered;

  /// Replayed and open, but not journalled: the old journal was kept, so the
  /// recovered text is still durable, and nothing typed from here is.
  ///
  /// `message` names the reason. The correct advice is Save As somewhere the
  /// state directory's problem does not apply, or relaunch — the offer will
  /// still be there.
  const factory RecoveryOutcome.degraded({
    required DocumentHandle handle,
    required String message,
  }) = RecoveryOutcome_Degraded;

  /// Nothing was opened and nothing was removed. The offer can be made again.
  const factory RecoveryOutcome.failed({required String message}) =
      RecoveryOutcome_Failed;
}

/// Why a write did not happen. One variant per message §Phase 4 asks for.
enum SaveFailure {
  /// The file is read-only. Offer Save As.
  readOnly,

  /// The directory will not take the file. Offer Save As.
  permissionDenied,

  /// The filesystem is full, or the user is over quota. Offer Save As.
  noSpace,

  /// The directory does not exist.
  noSuchDirectory,

  /// Anything else the operating system said.
  io,

  /// The document handle is not open.
  noSuchDocument,

  /// The document has never been saved and no path was given. The UI must ask
  /// for one; this is not an error so much as a question.
  noPath,
}

@freezed
sealed class SaveOutcome with _$SaveOutcome {
  const SaveOutcome._();

  const factory SaveOutcome.saved({
    required String path,
    required int bytes,

    /// The backup written alongside, if one was.
    BackupView? backup,
  }) = SaveOutcome_Saved;

  /// Nothing needed writing. Autosave hits this constantly and it is not news.
  const factory SaveOutcome.unchanged() = SaveOutcome_Unchanged;
  const factory SaveOutcome.failed({
    required SaveFailure failure,

    /// The file the user asked for, never the temporary one.
    required String path,

    /// Human-readable, and specific: it names the file and the reason.
    required String message,
  }) = SaveOutcome_Failed;
}

/// One script in the library (§6's `ScriptEntry`).
class ScriptView {
  final String id;
  final String path;
  final String title;

  /// Unix milliseconds. Dart formats it: a date's appearance is a locale
  /// question and the core has no locale.
  final int modifiedMillis;
  final int bytes;

  /// Zero until Phase 6's `layout` crate can count pages.
  final int pageCount;

  /// The file was not there when the library was last refreshed. Shown as
  /// missing, never dropped (§Phase 4).
  final bool missing;
  final bool open;
  final int scrollRow;

  const ScriptView({
    required this.id,
    required this.path,
    required this.title,
    required this.modifiedMillis,
    required this.bytes,
    required this.pageCount,
    required this.missing,
    required this.open,
    required this.scrollRow,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      modifiedMillis.hashCode ^
      bytes.hashCode ^
      pageCount.hashCode ^
      missing.hashCode ^
      open.hashCode ^
      scrollRow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          modifiedMillis == other.modifiedMillis &&
          bytes == other.bytes &&
          pageCount == other.pageCount &&
          missing == other.missing &&
          open == other.open &&
          scrollRow == other.scrollRow;
}
