// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'handshake.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `emit`, `event_sink`

CoreInfo coreInfo() => RustLib.instance.api.crateApiHandshakeCoreInfo();

/// Subscribe to the proof channel. The application subscribes to
/// `api::events::core_events` instead — see [`ProofEvent`].
Stream<ProofEvent> proofEvents() =>
    RustLib.instance.api.crateApiHandshakeProofEvents();

/// Ask the core to emit a [`ProofEvent::Pong`] **from another thread**, so the
/// test proves a genuine unsolicited push rather than a disguised return value.
///
/// Note there is no timer anywhere in this file: the stream is idle until
/// something happens, which is what the 0% idle CPU budget (§1.3) requires.
void ping({required String text}) =>
    RustLib.instance.api.crateApiHandshakePing(text: text);

/// Return `text` unchanged. The point is that "unchanged" survives a UTF-8
/// encode, an FFI hop, and a UTF-16 decode.
String echo({required String text}) =>
    RustLib.instance.api.crateApiHandshakeEcho(text: text);

TextMetrics textMetrics({required String text}) =>
    RustLib.instance.api.crateApiHandshakeTextMetrics(text: text);

/// Slice `text` by a **UTF-16** range, the way an editor command will (§3.4).
/// Returns `None` if the range is invalid — notably when an offset falls
/// between the halves of a surrogate pair.
String? sliceUtf16({
  required String text,
  required int startUtf16,
  required int endUtf16,
}) => RustLib.instance.api.crateApiHandshakeSliceUtf16(
  text: text,
  startUtf16: startUtf16,
  endUtf16: endUtf16,
);

/// What the core reports about itself at startup.
class CoreInfo {
  /// Version of the `bridge` crate — i.e. of the core as a whole.
  final String coreVersion;

  /// `flutter_rust_bridge` version the `.so` was generated against. If this
  /// ever disagrees with the Dart package version, the codegen is stale.
  final String frbVersion;

  /// The workspace crates, so the demo window can show the layering.
  final List<CrateInfo> crates;

  const CoreInfo({
    required this.coreVersion,
    required this.frbVersion,
    required this.crates,
  });

  @override
  int get hashCode =>
      coreVersion.hashCode ^ frbVersion.hashCode ^ crates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInfo &&
          runtimeType == other.runtimeType &&
          coreVersion == other.coreVersion &&
          frbVersion == other.frbVersion &&
          crates == other.crates;
}

/// One crate in the Rust workspace (§2.5).
class CrateInfo {
  final String name;
  final String role;

  /// Workspace crates this one is allowed to depend on. Empty means "nothing".
  final List<String> dependsOn;

  const CrateInfo({
    required this.name,
    required this.role,
    required this.dependsOn,
  });

  @override
  int get hashCode => name.hashCode ^ role.hashCode ^ dependsOn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrateInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          role == other.role &&
          dependsOn == other.dependsOn;
}

@freezed
sealed class ProofEvent with _$ProofEvent {
  const ProofEvent._();

  /// Emitted the moment Dart subscribes.
  const factory ProofEvent.ready({required String coreVersion}) =
      ProofEvent_Ready;

  /// Emitted from a worker thread in response to [`ping`].
  const factory ProofEvent.pong({required String text, required int lenUtf16}) =
      ProofEvent_Pong;
}

/// How the core measures a string. Dart asserts `len_utf16` against its own
/// `String.length`; if those ever disagree, every offset in the app is wrong.
class TextMetrics {
  final int lenUtf16;
  final int lenUtf8;
  final int charCount;

  const TextMetrics({
    required this.lenUtf16,
    required this.lenUtf8,
    required this.charCount,
  });

  @override
  int get hashCode => lenUtf16.hashCode ^ lenUtf8.hashCode ^ charCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextMetrics &&
          runtimeType == other.runtimeType &&
          lenUtf16 == other.lenUtf16 &&
          lenUtf8 == other.lenUtf8 &&
          charCount == other.charCount;
}
