// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'doc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'layout.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `changed_block`, `clamp_u32`, `fingerprint`, `fingerprints`, `line_view`, `page_config`, `page_view`, `paginate_snapshot`, `paginate`, `pagination_view`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Job`, `Planned`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// §6's `paginate`. Lays the document out on the page grid.
///
/// Async because it is the long job §2.3 has in mind: 50 ms for 120 pages
/// against the actor's 2 ms budget. Everything expensive happens between the
/// two actor visits, on the FRB worker thread this runs on.
Future<PaginationOutcome> docPaginate({
  required DocumentHandle handle,
  required PageSetup setup,
}) => RustLib.instance.api.crateApiLayoutDocPaginate(
  handle: handle,
  setup: setup,
);

/// A resolved printable run, shared with the PDF's emphasis interpretation.
class EmphasisRunView {
  final String text;
  final bool bold;
  final bool italic;
  final bool underline;

  const EmphasisRunView({
    required this.text,
    required this.bold,
    required this.italic,
    required this.underline,
  });

  @override
  int get hashCode =>
      text.hashCode ^ bold.hashCode ^ italic.hashCode ^ underline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmphasisRunView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bold == other.bold &&
          italic == other.italic &&
          underline == other.underline;
}

/// Why a positioned fragment exists. Mirrors `layout::LayoutLineKind`; the
/// duplication is deliberate, so that the engine's internal vocabulary can
/// change without changing the generated bindings (ADR 0020).
enum LayoutLineKind {
  content,
  blank,
  pageNumber,
  sceneNumberLeft,
  sceneNumberRight,

  /// The `(MORE)` under a speech that a page break interrupted.
  more,

  /// The `CHARACTER (CONT'D)` that resumes it overleaf.
  continued,
  title,
}

/// One printable fragment, placed on the grid.
///
/// `row` is relative to the top of the text area and `column` to its left edge.
/// Both may be negative: the page number sits above the text area and the scene
/// number gutters outside it.
class LayoutLineView {
  final int row;
  final int column;

  /// Raw text, already uppercased and wrapped, retained for source identity.
  final String content;

  /// Printable text and final output styles; no Fountain rescan is needed.
  final List<EmphasisRunView> runs;

  /// The block this came from, or `None` for generated furniture — a page
  /// number, a blank, a `(MORE)`. This is the identity a preview maps a click
  /// back to the editor with, and it is the same `BlockId` [`crate::api::doc`]
  /// speaks.
  final int? block;

  /// Which wrapped line of `block` this is, counting from zero. Absent
  /// wherever `block` is, and on furniture that belongs to a block without
  /// being any of its lines.
  final int? sourceLine;
  final LayoutLineKind kind;

  const LayoutLineView({
    required this.row,
    required this.column,
    required this.content,
    required this.runs,
    this.block,
    this.sourceLine,
    required this.kind,
  });

  @override
  int get hashCode =>
      row.hashCode ^
      column.hashCode ^
      content.hashCode ^
      runs.hashCode ^
      block.hashCode ^
      sourceLine.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutLineView &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          column == other.column &&
          content == other.content &&
          runs == other.runs &&
          block == other.block &&
          sourceLine == other.sourceLine &&
          kind == other.kind;
}

/// What to paginate for (§6's `PageConfig`).
class PageSetup {
  final PaperSize paper;
  final SceneNumbers sceneNumbers;
  final bool boldSceneHeadings;

  /// Shrinks the page to this many rows. For tests and the debug surface
  /// only: it makes a page break happen in three blocks instead of fifty, so
  /// a break rule can be looked at without a fifty-page fixture. A real
  /// preview or export leaves it `None`, and the rows come from the paper.
  final int? debugLinesPerPage;

  const PageSetup({
    required this.paper,
    required this.sceneNumbers,
    required this.boldSceneHeadings,
    this.debugLinesPerPage,
  });

  @override
  int get hashCode =>
      paper.hashCode ^
      sceneNumbers.hashCode ^
      boldSceneHeadings.hashCode ^
      debugLinesPerPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageSetup &&
          runtimeType == other.runtimeType &&
          paper == other.paper &&
          sceneNumbers == other.sceneNumbers &&
          boldSceneHeadings == other.boldSceneHeadings &&
          debugLinesPerPage == other.debugLinesPerPage;
}

/// One page. The title page has no number and is not in [`PaginationView::pages`],
/// so `pages[0]` is always screenplay page 1.
class PageView {
  final int? number;
  final List<LayoutLineView> lines;

  const PageView({this.number, required this.lines});

  @override
  int get hashCode => number.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageView &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          lines == other.lines;
}

@freezed
sealed class PaginationOutcome with _$PaginationOutcome {
  const PaginationOutcome._();

  /// The pagination describes the document as it stands.
  const factory PaginationOutcome.current({
    required PaginationView pagination,
  }) = PaginationOutcome_Current;

  /// The document was edited while this was being computed. It is a correct
  /// pagination of the text that was there when it started, and it is handed
  /// back rather than swallowed — a debug view still wants to see it, and a
  /// caller that silently got nothing would be worse. Nothing durable may be
  /// derived from it: the library's page count, in particular, keeps its
  /// previous value rather than taking this one (ADR 0020).
  const factory PaginationOutcome.stale({required PaginationView pagination}) =
      PaginationOutcome_Stale;

  /// The handle names no open document.
  const factory PaginationOutcome.noSuchDocument() =
      PaginationOutcome_NoSuchDocument;
}

/// Cache and fixed-point diagnostics (ADR 0022).
///
/// Not decoration: this is how a test proves a run was *incremental* rather
/// than merely correct, which is a claim no assertion about the pages can make.
class PaginationStats {
  final int blockHits;
  final int blockMisses;

  /// Pages before the change that were kept, having been proved equal.
  final int reusedPages;

  /// Pages after it that were.
  final int reusedTailPages;
  final int breakRuleIterations;

  /// The break-rule loop did not converge inside its cap and the naive fill
  /// was used. Always false in practice; §5.4 requires it to be reportable.
  final bool fellBackToNaive;

  /// The block the engine was told had changed, if it was told anything. A
  /// full pagination was asked for when this is `None`.
  final int? hintedBlock;

  const PaginationStats({
    required this.blockHits,
    required this.blockMisses,
    required this.reusedPages,
    required this.reusedTailPages,
    required this.breakRuleIterations,
    required this.fellBackToNaive,
    this.hintedBlock,
  });

  @override
  int get hashCode =>
      blockHits.hashCode ^
      blockMisses.hashCode ^
      reusedPages.hashCode ^
      reusedTailPages.hashCode ^
      breakRuleIterations.hashCode ^
      fellBackToNaive.hashCode ^
      hintedBlock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginationStats &&
          runtimeType == other.runtimeType &&
          blockHits == other.blockHits &&
          blockMisses == other.blockMisses &&
          reusedPages == other.reusedPages &&
          reusedTailPages == other.reusedTailPages &&
          breakRuleIterations == other.breakRuleIterations &&
          fellBackToNaive == other.fellBackToNaive &&
          hintedBlock == other.hintedBlock;
}

/// A complete pagination (§6's `PaginatedScript`).
class PaginationView {
  /// The document revision this describes. Moves backwards on undo, which is
  /// why it is not what staleness is judged by — see `generation`.
  final int revision;

  /// The monotonic document generation this describes. Two paginations of one
  /// handle with the same generation describe the same text.
  final int generation;
  final int pageCount;
  final PageView? titlePage;
  final List<PageView> pages;
  final PaginationStats stats;

  const PaginationView({
    required this.revision,
    required this.generation,
    required this.pageCount,
    this.titlePage,
    required this.pages,
    required this.stats,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      generation.hashCode ^
      pageCount.hashCode ^
      titlePage.hashCode ^
      pages.hashCode ^
      stats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginationView &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          generation == other.generation &&
          pageCount == other.pageCount &&
          titlePage == other.titlePage &&
          pages == other.pages &&
          stats == other.stats;
}

/// The paper a pagination is measured against (§5.2).
enum PaperSize { usLetter, a4 }

/// Which scene-number gutters the result should carry (§5.3).
enum SceneNumbers { off, left, right, both }
