// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'doc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'spell.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `accepted_words`, `cache_key`, `display_language`, `ensure_project_loaded`, `fingerprint`, `initialise_from`, `initialise`, `key_for`, `misspelling_views`, `plan`, `stale`, `status_view`, `write_words`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CheckPlan`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

SpellStatus spellStatus() => RustLib.instance.api.crateApiSpellSpellStatus();

/// Enables/disables checking or selects an installed language.
///
/// Dictionary parsing happens here, off the actor. A failed selection leaves
/// the previously working dictionary selected and reports failure.
Future<SpellActionResult> spellConfigure({
  required bool enabled,
  String? language,
}) => RustLib.instance.api.crateApiSpellSpellConfigure(
  enabled: enabled,
  language: language,
);

/// §6's async `spell_check_block`.
Future<SpellCheckResult> spellCheckBlock({
  required DocumentHandle handle,
  required int block,
}) => RustLib.instance.api.crateApiSpellSpellCheckBlock(
  handle: handle,
  block: block,
);

Future<List<String>> spellSuggest({required String word}) =>
    RustLib.instance.api.crateApiSpellSpellSuggest(word: word);

/// Ignores only the exact occurrence under the context menu.
SpellActionResult spellIgnoreOnce({
  required DocumentHandle handle,
  required int block,
  required int startUtf16,
  required int endUtf16,
  required String word,
}) => RustLib.instance.api.crateApiSpellSpellIgnoreOnce(
  handle: handle,
  block: block,
  startUtf16: startUtf16,
  endUtf16: endUtf16,
  word: word,
);

SpellActionResult spellIgnoreAll({
  required DocumentHandle handle,
  required String word,
}) => RustLib.instance.api.crateApiSpellSpellIgnoreAll(
  handle: handle,
  word: word,
);

Future<SpellActionResult> spellAddPersonal({required String word}) =>
    RustLib.instance.api.crateApiSpellSpellAddPersonal(word: word);

Future<SpellActionResult> spellAddProject({
  required DocumentHandle handle,
  required String word,
}) => RustLib.instance.api.crateApiSpellSpellAddProject(
  handle: handle,
  word: word,
);

/// One underline in a block, in the bridge's UTF-16 coordinates.
class Misspelling {
  final int block;
  final int startUtf16;
  final int endUtf16;
  final String word;

  const Misspelling({
    required this.block,
    required this.startUtf16,
    required this.endUtf16,
    required this.word,
  });

  @override
  int get hashCode =>
      block.hashCode ^ startUtf16.hashCode ^ endUtf16.hashCode ^ word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Misspelling &&
          runtimeType == other.runtimeType &&
          block == other.block &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16 &&
          word == other.word;
}

@freezed
sealed class SpellActionResult with _$SpellActionResult {
  const SpellActionResult._();

  const factory SpellActionResult.applied() = SpellActionResult_Applied;
  const factory SpellActionResult.noSuchDocument() =
      SpellActionResult_NoSuchDocument;
  const factory SpellActionResult.noScriptPath() =
      SpellActionResult_NoScriptPath;
  const factory SpellActionResult.failed({required String message}) =
      SpellActionResult_Failed;
}

/// One asynchronous block answer.
class SpellCheckResult {
  final int block;

  /// False when the block changed while its snapshot was being checked, or
  /// the handle/block no longer exists. Dart discards the whole answer.
  final bool current;

  /// True when the expensive checker did not run because this exact block
  /// hash/configuration was already cached.
  final bool cached;
  final List<Misspelling> misspellings;

  const SpellCheckResult({
    required this.block,
    required this.current,
    required this.cached,
    required this.misspellings,
  });

  @override
  int get hashCode =>
      block.hashCode ^
      current.hashCode ^
      cached.hashCode ^
      misspellings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpellCheckResult &&
          runtimeType == other.runtimeType &&
          block == other.block &&
          current == other.current &&
          cached == other.cached &&
          misspellings == other.misspellings;
}

/// One installed language for the selector.
class SpellLanguage {
  final String code;
  final String label;

  const SpellLanguage({required this.code, required this.label});

  @override
  int get hashCode => code.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpellLanguage &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          label == other.label;
}

/// The complete UI state of spell checking.
class SpellStatus {
  final bool enabled;
  final String? language;
  final List<SpellLanguage> languages;

  /// Always useful: selected language, disabled state, or why none can run.
  final String message;

  const SpellStatus({
    required this.enabled,
    this.language,
    required this.languages,
    required this.message,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      language.hashCode ^
      languages.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpellStatus &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          language == other.language &&
          languages == other.languages &&
          message == other.message;
}
